# Generated by Django 3.1.2 on 2020-10-27 10:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Investor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstname', models.CharField(max_length=100, verbose_name='Имя')),
                ('lastname', models.CharField(max_length=100, verbose_name='Фамилия')),
                ('patronymic', models.CharField(max_length=100, verbose_name='Отчество')),
                ('qualification_status', models.CharField(choices=[('Identified', 'Identified'), ('Agreed', 'Agreed'), ('Qualificated', 'Qualificated'), ('Refused to qualify', 'Refused to qualify')], max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Passport',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstname', models.CharField(max_length=100, verbose_name='Имя')),
                ('lastname', models.CharField(max_length=100, verbose_name='Фамилия')),
                ('patronymic', models.CharField(max_length=100, verbose_name='Отчество')),
                ('birth_date', models.DateField()),
                ('number', models.IntegerField(verbose_name='Номер')),
                ('series', models.IntegerField(verbose_name='Серия')),
                ('issued_by', models.CharField(max_length=100, verbose_name='Кем выдан')),
                ('date_of_issue', models.DateField()),
                ('registration_address', models.CharField(max_length=100, verbose_name='Адрес регистрации')),
                ('department_code', models.CharField(max_length=10, verbose_name='Код подразделения')),
                ('file', models.FileField(null=True, upload_to='media/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('investor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='passports', to='qualification.investor')),
            ],
        ),
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Название')),
                ('file', models.FileField(null=True, upload_to='media/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('investor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='documents', to='qualification.investor')),
            ],
        ),
    ]
