# Generated by Django 3.1.2 on 2020-10-27 12:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('qualification', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='passport',
            name='birth_date',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='passport',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='passport',
            name='date_of_issue',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='passport',
            name='department_code',
            field=models.CharField(max_length=10, null=True, verbose_name='Код подразделения'),
        ),
        migrations.AlterField(
            model_name='passport',
            name='firstname',
            field=models.CharField(max_length=100, null=True, verbose_name='Имя'),
        ),
        migrations.AlterField(
            model_name='passport',
            name='investor',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='passports', to='qualification.investor'),
        ),
        migrations.AlterField(
            model_name='passport',
            name='issued_by',
            field=models.CharField(max_length=100, null=True, verbose_name='Кем выдан'),
        ),
        migrations.AlterField(
            model_name='passport',
            name='lastname',
            field=models.CharField(max_length=100, null=True, verbose_name='Фамилия'),
        ),
        migrations.AlterField(
            model_name='passport',
            name='number',
            field=models.IntegerField(null=True, verbose_name='Номер'),
        ),
        migrations.AlterField(
            model_name='passport',
            name='patronymic',
            field=models.CharField(max_length=100, null=True, verbose_name='Отчество'),
        ),
        migrations.AlterField(
            model_name='passport',
            name='registration_address',
            field=models.CharField(max_length=100, null=True, verbose_name='Адрес регистрации'),
        ),
        migrations.AlterField(
            model_name='passport',
            name='series',
            field=models.IntegerField(null=True, verbose_name='Серия'),
        ),
    ]
